language: elixir
elixir:
  - 1.4.0
otp_release:
  - 19.2
addons:
  postgresql: "9.4"
sudo: false
before_script:
  - mix deps.get --only test
script:
  - mix test
notifications:
  recipients:
    - brittonbroderick@gmail.com
